server:
  port: 8084
hm:
  swagger:
    title: 订单服务接口文档
    package: com.jndx.trade.controller
  db:
    database: hm-trade
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123